name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.15
  - pyyaml
  - hydra-core=1.3.2
  - pip=24.3.1
  - pip:
      - mlflow==2.9.2
      - wandb==0.15.12
      - hydra-core==1.3.2
      - pandas==1.5.3
      - numpy==1.26.4
      - scikit-learn==1.1.3
      - matplotlib==3.6.3
