name: train_random_forest
channels:
  - conda-forge
dependencies:
  - python=3.9.15
  - pip=24.3.1
  - pandas=1.5.3
  - numpy=1.26.4
  - scipy=1.10.1
  - scikit-learn=1.1.3
  - matplotlib=3.6.3
  - pip:
      - mlflow==2.9.2
      - wandb==0.15.12
